Install dependencies in vendor workflow
Install dependencies to avoid

```
Run script/dump-detect-json-fixture
<internal:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- licensee (LoadError)
	from <internal:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from script/dump-detect-json-fixture:5:in `<main>'
Error: Process completed with exit code 1.
```